-- ==============================================================================
-- Schema for MyInvestmentBanker Vector & Relational Database (Supabase Postgres)
-- Run this script inside the Supabase SQL Editor.
-- ==============================================================================

-- Enable the pgvector extension for semantic search (RAG)
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Portfolio Holdings Table
CREATE TABLE IF NOT EXISTS portfolio_holdings (
    symbol VARCHAR(12) PRIMARY KEY, -- Stock ticker (e.g., 'AAPL', 'MSFT')
    name VARCHAR(255),
    quantity NUMERIC(15, 4) NOT NULL DEFAULT 0,
    cost_basis NUMERIC(15, 4) NOT NULL DEFAULT 0, -- Average purchase price
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger to auto-update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_portfolio_holdings_modtime
    BEFORE UPDATE ON portfolio_holdings
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


-- 2. User Investment Thesis Table
-- Stores your personal thesis on why you hold each stock
CREATE TABLE IF NOT EXISTS investment_thesis (
    symbol VARCHAR(12) PRIMARY KEY REFERENCES portfolio_holdings(symbol) ON DELETE CASCADE,
    thesis_text TEXT NOT NULL,
    -- Vector embedding (768 dimensions for Gemini text-embedding-004)
    thesis_vector vector(768),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_investment_thesis_modtime
    BEFORE UPDATE ON investment_thesis
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


-- 3. Cognitive Memory: Corporate Analyst Memos
-- Stores past quarterly and event memos generated by the CFA Agent
CREATE TABLE IF NOT EXISTS corporate_analyst_memos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol VARCHAR(12) NOT NULL REFERENCES portfolio_holdings(symbol) ON DELETE CASCADE,
    period VARCHAR(20) NOT NULL, -- e.g., 'FY2025', 'Q1_2026', 'EVENT_VOLATILITY'
    memo_text TEXT NOT NULL,
    metrics JSONB, -- key-value store of financial metrics: FCF, Debt/Equity, margins, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memos_symbol ON corporate_analyst_memos(symbol);


-- 4. News Digests & RAG Table
-- Caches daily financial news bulletins to prevent redundant processing & allow semantic search
CREATE TABLE IF NOT EXISTS news_digests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol VARCHAR(12) NOT NULL REFERENCES portfolio_holdings(symbol) ON DELETE CASCADE,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    article_vector vector(768), -- Embedding of the summarized news
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_news_symbol ON news_digests(symbol);
-- HNSW Vector Index for efficient semantic RAG searches (on cosine distance)
CREATE INDEX IF NOT EXISTS idx_news_vector ON news_digests USING hnsw (article_vector vector_cosine_ops);


-- 5. User Profile & Preferences Key-Value Store
CREATE TABLE IF NOT EXISTS user_preferences (
    key VARCHAR(255) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 6. Short-Term Memory: Secure Chat Logs & Checkpoints
CREATE TABLE IF NOT EXISTS chat_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL, -- 'user' or 'assistant'
    message TEXT NOT NULL,
    metadata JSONB, -- stores Telegram details, custom keyboards, state metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_user ON chat_logs(user_id);
